Feature/addsubdomain
hsridharan/AzureMonitorForSAPSolutions pull request #1
Opened 2020-12-14 17:04 UTC by hsridharan

2020-12-14 17:48 UTC, MikeFrei commented on sapmon/payload/provider/sapnetweaver.py
> +                      self.providerInstance.getPortFromInstanceNr(self.providerInstance.sapInstanceNr),
I think that as long as you are in a parentheses block you do not need to use '\' to wrap lines.  And in this case anyway you have the '\' on the first line but not the second, so perhaps you can just remove?

2020-12-14 18:03 UTC, MikeFrei commented on sapmon/payload/provider/sapnetweaver.py
> +            if len(host) > 2:
sorry if this is ignorant python question but it looks like you're declaring this variable within the if/else scope, but then you're using it below.  I would have expected this would only work if the variable was first declared outside the if/else scope and then set to a value within the if/else block.

2020-12-14 18:06 UTC, MikeFrei commented on sapmon/payload/provider/sapnetweaver.py
> +            if 'sapSubdomain' in self.providerInstance.providerProperties:
should you do a check here to ensure not only that it is defined but that it is non-empty?  otherwise you might be appending a '.' followed by nothing below?

2020-12-14 18:12 UTC, MikeFrei commented on sapmon/payload/provider/sapnetweaver.py
> +            hostname = hostname + "." + subDomain
this first jumps out at me because it looks like you're checking for initialization after you've just ensured the property was initialized, but on closer look I can see that it may be necessary because the self.sapSubDomain property may still be empty.

Maybe instead you could do:

if subDomain:
    hostname = hostname + "." + subDomain
elif self.sapSubDomain:
    hostname = hostname + "." + self.sapSubDomain

2020-12-14 18:13 UTC, MikeFrei commented on sapmon/payload/provider/sapnetweaver.py
> +            if len(host) > 2:
nevermind I can see we were already doing this in other parts of the code before your change so it looks like this notion of variable scoping in python is a little different from what I am accustomed to

2020-12-14 18:14 UTC, MikeFrei commented on sapmon/payload/provider/sapnetweaver.py
> +        self.tracer.info("[%s] fetching current timestamp from message server" % self.fullName)
thank you for fixing!

2020-12-14 18:23 UTC, MikeFrei commented on sapmon/payload/provider/sapnetweaver.py
>              hostname, port = host[0], host[1]
just an observation:  if you were to ensure that each record in hosts had 3 values (and just have 'None' when no subDomain is specified) then you could remove this if statement and just have:

hostname, port, subDomain = host[0], host[1], host[2]

2020-12-14 18:27 UTC, MikeFrei commented on sapmon/payload/provider/sapnetweaver.py
> +                      self.providerInstance.getPortFromInstanceNr(self.providerInstance.sapInstanceNr),
also another comment here (related to comment below).  It would probably be much better (for consistency reasons and also for future changes) to always ensure that each host instance record always has the same amount of values in it, even if some of those values have None.  So in this case, you can remove this if and ensure that the hosts entry has all 3 values (you will also have to change the else block below).

This will insulate you from future changes where you might want to add some 4th property to a hosts config record and now suddenly you cannot easily deal with situation where you can have an optional 3rd property.

2020-12-14 18:27 UTC, MikeFrei requested changes
happy to talk about these in person or over teams if you like

2020-12-14 18:49 UTC, jasneetbhatti-msft commented on sapmon/payload/provider/sapnetweaver.py
> -
Please add back the newline separator

2020-12-14 18:55 UTC, jasneetbhatti-msft commented on sapmon/payload/provider/sapnetweaver.py
> +                subDomain = None
By this point in the execution, `self.sapSubdomain` already contains either `None` or a valid value because of the line
```
self.sapSubDomain = self.providerProperties.get("sapSubdomain", None)
```
in `parseProperties`.
So you could just do
```
hosts = [(self.providerInstance.sapHostName, \
               self.providerInstance.getPortFromInstanceNr(self.providerInstance.sapInstanceNr)), self.providerInstance.sapSubDomain)]
```
directly without any if-else conditions

This will eliminate your length check entirely.

2020-12-14 18:56 UTC, jasneetbhatti-msft commented on sapmon/payload/provider/sapnetweaver.py
> +                      self.providerInstance.getPortFromInstanceNr(self.providerInstance.sapInstanceNr),
See my comment below about this

2020-12-14 19:20 UTC, hsridharan commented on sapmon/payload/provider/sapnetweaver.py
> +            if len(host) > 2:
It seems to be working @MikeFrei , but I am happy to update it that's the convention. May be @jasneetbhatti-msft  can guide us here.

2020-12-14 19:27 UTC, jasneetbhatti-msft requested changes
I couldn't add this comment on the specific line directly due to some limitation of github, so sharing it here.

For this line in _getServerTimestamp
```
self.tracer.error("[%s] suppressing error during HTTP GET request to url %s: %s " % (self.fullName, message_server_endpoint, e))
```
replace it with
```
self.tracer.info("[%s] suppressing expected error while fetching server time during HTTP GET request to url %s: %s " % (self.fullName, message_server_endpoint, e))
```

This is better suited as an info message rather than an error since we expect it to fail.

2020-12-14 19:27 UTC, jasneetbhatti-msft commented on sapmon/payload/provider/sapnetweaver.py
> +            hostname = hostname + "." + subDomain
Also make sure you handle the case when subdomain is empty. Otherwise you might end up with `hostname.`

2020-12-14 19:27 UTC, jasneetbhatti-msft commented on sapmon/payload/provider/sapnetweaver.py
> +            if 'sapSubdomain' in self.providerInstance.providerProperties:
As a general rule, you shouldn't have to access `self.providerInstance.providerProperties` at any place except the `parseProperties` method. If you are having to, then it means that there is some flaw.
Wherever required, you should use `self.providerInstance.sapSubdomain`

2020-12-14 19:27 UTC, jasneetbhatti-msft commented on sapmon/payload/provider/sapnetweaver.py
> +        self.sapSubDomain = None
The popular convention seems to be: `sapSubdomain`/`subdomain`. The `d` should be lowercase. Please update all occurences accordingly.

2020-12-14 19:27 UTC, jasneetbhatti-msft commented on sapmon/payload/provider/sapnetweaver.py
> +        if subDomain :
Please remove the extra whitespace before `:`

2020-12-14 19:27 UTC, jasneetbhatti-msft commented on sapmon/payload/provider/sapnetweaver.py
> +            if 'subDomain' not in instance:
Isn't this always going to be true ? I don't see any place where you're setting subdomain in the instance list.
You shouldn't be looking for it in the instance list. Just directly use `self.sapSubdomain`

2020-12-14 19:27 UTC, jasneetbhatti-msft commented on sapmon/payload/provider/sapnetweaver.py
> +                    result['subDomain'] = instance['subDomain']
You could add this in the `_actionGetSystemInstanceList` method too so that both methods report this field

2020-12-14 20:13 UTC, jasneetbhatti-msft requested changes
Also account for the scenario where the customer provided an ip address as hostname instead of a server name.
In that case, you should avoid appending the subdomain even if provided.

After the first time we pull the instance list, the state file will contain text hostnames and thereafter you can start appending subdomain if provided.

You basically need to handle it for the first run of the provider.

2020-12-14 20:45 UTC, hsridharan commented on sapmon/payload/provider/sapnetweaver.py
>              hostname, port = host[0], host[1]
@MikeFrei - I tried that but if the subdomain is not provided then host[2] will throw an exception. So, I am checking len(host) and determining whether it has a subdomain or not, and then assigning the value to local

2020-12-14 21:00 UTC, hsridharan commented on sapmon/payload/provider/sapnetweaver.py
> +                      self.providerInstance.getPortFromInstanceNr(self.providerInstance.sapInstanceNr),
Makes sense. Updated.

2020-12-14 21:01 UTC, hsridharan commented on sapmon/payload/provider/sapnetweaver.py
> +            if 'sapSubdomain' in self.providerInstance.providerProperties:
Updated

2020-12-14 21:01 UTC, hsridharan commented on sapmon/payload/provider/sapnetweaver.py
> +        self.lastRunLocal = datetime.utcnow()
done

2020-12-14 21:01 UTC, hsridharan commented on sapmon/payload/provider/sapnetweaver.py
> +        self.lastRunLocal = datetime.utcnow()
done

2020-12-14 21:02 UTC, hsridharan commented on sapmon/payload/provider/sapnetweaver.py
> +        self.sapSubDomain = None
done

2020-12-14 21:02 UTC, hsridharan commented on sapmon/payload/provider/sapnetweaver.py
> +        if subDomain :
done

2020-12-14 21:08 UTC, hsridharan commented on sapmon/payload/provider/sapnetweaver.py
> -
okay. Added

2020-12-14 22:00 UTC, hsridharan commented on sapmon/payload/provider/sapnetweaver.py
> +            if 'subDomain' not in instance:
Yes - that's correct, but since the self.sapSubdomain is not populated now I am reading it from self.providerInstance.sapSubdomain. Hope that's okay?

2020-12-14 22:00 UTC, hsridharan commented on sapmon/payload/provider/sapnetweaver.py
> +                    result['subDomain'] = instance['subDomain']
done

2020-12-14 23:23 UTC, hsridharan commented on sapmon/payload/provider/sapnetweaver.py
> +            hostname = hostname + "." + subDomain
I am assigning if self.sapSubDomain to subDomain and then concatenating hostname and subDomain. So if subDomain is empty it won't add "." to the hostname, Kindly double-check the logic once because it seems to be working fine for me.

2020-12-14 23:25 UTC, hsridharan commented on sapmon/payload/provider/sapnetweaver.py
>              hostname, port = host[0], host[1]
Modified the code to include subdomain always from parent method

2020-12-15 18:32 UTC, MikeFrei approved these changes

2020-12-15 19:22 UTC, jasneetbhatti-msft approved these changes

2020-12-15 19:39 UTC, rohPatil approved these changes

2020-12-19 00:52 UTC, persiaAziz commented
I see the PR is raised against the master branch of the forked repo? Is the intention to merge with the main repo? If yes, then please raise PR against the main repo. Tobias and I can review it there.

2021-01-06 04:39 UTC, merged