Added check in SapNetweaver to get computer name and azure resource mapping for aiops
hsridharan/AzureMonitorForSAPSolutions pull request #14
Opened 2021-09-03 12:59 UTC by amitsharma24

2021-09-06 07:08 UTC, saleelpk commented on sapmon/content/SapNetweaver.json
> +            "name": "SAP_VM_Mapping",
Nit: Rename to SAP_Host_AzRId_Mapping if it makes sense.

2021-09-06 07:14 UTC, saleelpk commented on sapmon/payload/provider/sapnetweaver.py
> +            self.tracer.info("%s AIOps is not enabled. Skipping check GetSapVmMapping", self.logTag)
Are we missing a return statement here?

2021-09-06 08:55 UTC, saleelpk commented on sapmon/payload/provider/sapnetweaver.py
> +    def _sanitizeGetEnvironmentDetails(self, records: List[str]) -> list:
Do you plan to handle Linux level parsing here?

2021-09-06 09:05 UTC, saleelpk commented on sapmon/payload/provider/sapnetweaver.py
> +        return {"computerName" : computerName}
Shouldn't this be wrapped in a list? The caller is extending all_results using the value returned from here on line 948.

2021-09-06 09:30 UTC, saleelpk commented on sapmon/payload/provider/sapnetweaver.py
> +        vmIds = instancesFiltered[0].vmIds
I'm assuming you meant vNetIds instead of vmIds.

2021-09-06 09:31 UTC, saleelpk commented on sapmon/payload/provider/sapnetweaver.py
> +        instancesFiltered = list(filter(
Nit: Rename to aiopsInstance?

2021-09-06 09:38 UTC, saleelpk commented on sapmon/payload/provider/sapnetweaver.py
> +        mappingKey = "computerName"
Nit: mappingKey would be dynamic right? For windows it is computerName, for Linux it could be different. If you are mapping it to computerName always, then maybe we don't need this variable?

2021-09-06 09:42 UTC, saleelpk commented on sapmon/payload/provider/sapnetweaver.py
> +        mergedResources = self._mergeDatasets(sapResources, azResources, mappingKey)
azResources would contain the computerName property. Do we need to merge the datasets?

2021-09-06 09:42 UTC, saleelpk commented on sapmon/payload/provider/sapnetweaver.py
> +    def _updateStateWithSapAzMapping(self, SapAzResourceMapping: List[Dict]) -> bool:
Nit: camel case?

2021-09-06 09:52 UTC, saleelpk commented on sapmon/payload/provider/sapnetweaver.py
> +            if(armType not in processedSapAzResourceMapping):
Nit: Use setdefault instead? Refer: https://docs.python.org/3/library/stdtypes.html#dict.setdefault

2021-09-06 09:54 UTC, saleelpk commented on sapmon/payload/provider/sapnetweaver.py
> +        processedSapAzResourceMapping = dict()
Use {} instead? I believe this is better in terms of performance

2021-09-06 09:54 UTC, amitsharma24 commented on sapmon/payload/provider/sapnetweaver.py
> +        return {"computerName" : computerName}
this would return a single object and the parser takes care of converting it into a list. There are 2 parsers available, one for a list and another for an object.

2021-09-06 09:54 UTC, amitsharma24 commented on sapmon/payload/provider/sapnetweaver.py
> +        vmIds = instancesFiltered[0].vmIds
yup. will update that

2021-09-06 09:55 UTC, amitsharma24 commented on sapmon/payload/provider/sapnetweaver.py
> +        instancesFiltered = list(filter(
agree

2021-09-06 09:56 UTC, saleelpk commented on sapmon/payload/provider/sapnetweaver.py
> +            key = resource["hostname"] + "_" + str(resource["instanceNr"]).zfill(2)
Nit: rename to instanceName? Alternatively, keep the same name and add a comment.

2021-09-06 09:56 UTC, amitsharma24 commented on sapmon/payload/provider/sapnetweaver.py
> +    def _updateStateWithSapAzMapping(self, SapAzResourceMapping: List[Dict]) -> bool:
will update

2021-09-06 09:57 UTC, amitsharma24 commented on sapmon/payload/provider/sapnetweaver.py
> +            key = resource["hostname"] + "_" + str(resource["instanceNr"]).zfill(2)
agree

2021-09-06 09:58 UTC, saleelpk commented on sapmon/payload/provider/sapnetweaver.py
> +            if("AzResourceConfig" in self.providerInstance.state):
Nit: If we can use the get method, we can get rid of the two nested ifs. Refer: https://python-reference.readthedocs.io/en/latest/docs/dict/get.html

2021-09-06 10:04 UTC, amitsharma24 commented on sapmon/payload/provider/sapnetweaver.py
> +            self.tracer.info("%s AIOps is not enabled. Skipping check GetSapVmMapping", self.logTag)
current design sets lastResult in _executeWebServiceRequest, so there is no more action pending, so no return

2021-09-06 10:04 UTC, amitsharma24 commented on sapmon/content/SapNetweaver.json
> +            "name": "SAP_VM_Mapping",
Sure. makes sense

2021-09-06 10:08 UTC, saleelpk commented on sapmon/payload/provider/sapnetweaver.py
> +        return {"computerName" : computerName}
Got it.

2021-09-06 10:31 UTC, saleelpk commented on sapmon/payload/provider/sapnetweaver.py
> +            if("AzResourceConfig" in self.providerInstance.state):
As discussed, the ARG call would either fail fully or not fail at all. In case of completed failures, the instance names would be required to filter the current mapping.

2021-09-06 10:33 UTC, saleelpk commented on sapmon/payload/provider/sapnetweaver.py
> +                if data1[key] == data2[key]:
Use outer join so that we don't miss any data.

2021-09-06 10:34 UTC, saleelpk commented on sapmon/payload/provider/sapnetweaver.py
> +            if("AzResourceConfig" in self.providerInstance.state):
Additionally, if there is a missing vNet, we might get partial results.

2021-09-07 12:58 UTC, amitsharma24 commented on sapmon/payload/provider/sapnetweaver.py
> +        mergedResources = self._mergeDatasets(sapResources, azResources, mappingKey)
yes, we need instance name (hostname and instance number) as key to other tables in LA

2021-09-22 06:35 UTC, amitsharma24 commented on sapmon/payload/provider/sapnetweaver.py
> +            self.tracer.info("%s AIOps is not enabled. Skipping check GetSapVmMapping", self.logTag)
added else statement for the rest of the logic

2021-09-22 07:46 UTC, amitsharma24 commented on sapmon/payload/provider/sapnetweaver.py
> +            if("AzResourceConfig" in self.providerInstance.state):
done

2021-09-22 07:47 UTC, amitsharma24 commented on sapmon/payload/provider/sapnetweaver.py
> +            if("AzResourceConfig" in self.providerInstance.state):
changed join logic to use left outer join, so that we always get instance names

2021-09-22 07:48 UTC, amitsharma24 commented on sapmon/payload/provider/sapnetweaver.py
> +                if data1[key] == data2[key]:
changed join logic to use left outer join, so that we always get instance names

2021-09-22 07:48 UTC, amitsharma24 commented on sapmon/payload/provider/sapnetweaver.py
> +            if(armType not in processedSapAzResourceMapping):
done

2021-09-27 18:25 UTC, amitsharma24 commented on sapmon/payload/provider/sapnetweaver.py
> +        pass
remove this line

2021-10-04 15:52 UTC, MikeFrei commented on sapmon/payload/provider/sapnetweaver.py
> +            self.tracer.info("%s AIOps is enabled. Running check SAP_Host_AzRId_Mapping", self.logTag)
you're not actually skipping anything if AIOps is disabled.  You just write an info log and then continue to execute this method anyway.

Also, I *think* a better way of doing this would be to integrate this check into the isEnabled() method above.  The reason why is because by putting the explicit enable check in side the action method itself, you are ensuring that the sapmon framework will still call this method (and this generates some additional log spam before and after).  Whereas if you put this check inside the isEnabled() method, similar to how things work for the RFC methods, then the sapmon framework will skip calling this action entirely.

2021-10-04 16:01 UTC, MikeFrei commented on sapmon/payload/provider/sapnetweaver.py
> +    def _updateStateWithSapAzMapping(self, sapAzResourceMapping: List[Dict]) -> bool:
sorry for not noticing this before now but I think you really need some logging in this function to not only track progress but output individual request latency and total batch latency.  Basically, assume the worst here (that this API starts experiencing high latency or timeouts, or you have unexpected surge of changed/new resources that you suddenly need to query ARM for.  And now running this simple action is taking several minutes or longer.  Or throwing some exception on a specific resource ID.

How are you going to debug and answer questions like how many resources was I trying to process?  How many did I get through successfully?  Am I having really high latency on this API?  Is there a specific ID that is causing this API to throw an error?  Am I able to successfully call this API at all?

2021-10-04 16:04 UTC, MikeFrei commented on sapmon/payload/provider/sapnetweaver.py
> +    def _getSapAzResourceMapping(self, sapResources: List[Dict]) -> List[Dict]:
this function itself is not calling any remote dependencies directly and so you don't necessarily need request latency success/error logging here, however, you are doing some logic to merge data sets and it might be very useful for being able to answer future debugging questions like "is this AIOps feature working at all?" or "Why does AIOps appear to not be able to establish any SAP instance -> Azure VM mappings for my SAP system?"

So some basic logging on the before/after outcome of the joined data sets might be useful

2021-10-04 16:11 UTC, MikeFrei commented on sapmon/payload/provider/sapnetweaver.py
> +    def _postProcessGetEnvironmentResults(self, sapResources: List[Dict]) -> List[Dict]:
The more I look at this, the more I think perhaps making the _postProcessXXXX lambda go invoke a bunch of remote service dependencies may not be the best design here.  In part because by calling this from within the _executeSoapApiAgainstAllInstances method you make the SOAP API itself appear to be responsible for increased latency or exceptions  when in fact it could have been coming from your post processing function.

Your post processing is not actually tracking/logging latency, which is another critical thing.  I think by doing it the way you did, it enabled you to keep your _action method small and looking very similar to the other SOAP API ones, but in this case you have a special case API here and I think it might have been cleaner to do all this additional post processing that involves remote dependency calls as another set of logic invoked from your action method directly.

2021-10-04 16:15 UTC, MikeFrei commented on sapmon/payload/provider/sapnetweaver.py
> +            postProcessResultsFunc = lambda results: self._postProcessGetEnvironmentResults(results)
see comment below about rethinking this design of having a post processing function invoked from the _executeSoapApiForInstances method where that post processing method itself involves extensive remote dependency calls.

2021-10-04 16:18 UTC, MikeFrei requested changes
several areas missing logging that might be critical to debugging if your new feature is running as expected.

Also, most critically, the check for whether the new AIOps action is enabled is not actually skipping the execution of the action.  Please see my comment about this.  I think it is cleaner to simply integrate into the existing isEnabled() override method

2021-10-05 06:53 UTC, amitsharma24 commented on sapmon/payload/provider/sapnetweaver.py
> +        mappingKey = "computerName"
this is removed

2021-10-05 07:20 UTC, amitsharma24 commented on sapmon/payload/provider/sapnetweaver.py
> +            self.tracer.info("%s AIOps is enabled. Running check SAP_Host_AzRId_Mapping", self.logTag)
i have moved this logic to isEnabled()
only reason why I had kept it within the action method was to reduce touchpoints in the code, as this logic would be removed after v0, but I agree to your point, having this logic in isEnabled() will ensure this action doesnt get called at all when aiops isnt enabled.

2021-10-05 07:44 UTC, amitsharma24 commented on sapmon/payload/provider/sapnetweaver.py
> +    def _updateStateWithSapAzMapping(self, sapAzResourceMapping: List[Dict]) -> bool:
sorry if i havent understood this comment correctly, but there are no API calls in this method. I have added logging to other methods where api calls are being made (logging latency and results).
But i had one question, is it okay to log these results? Since this is customer data, is it okay to log all of this information?

2021-10-05 07:47 UTC, amitsharma24 commented on sapmon/payload/provider/sapnetweaver.py
> +    def _getAzResourceId(self, computerNames: List[str], vNetIds: List[str]) -> List[Dict[str, str]]:
i have added logs before and after calling this method in _getSapAzResourceMapping

2021-10-05 07:49 UTC, amitsharma24 commented on sapmon/payload/provider/sapnetweaver.py
> +    def _getSapAzResourceMapping(self, sapResources: List[Dict]) -> List[Dict]:
added logs for input and output data within this method

2021-10-05 07:51 UTC, amitsharma24 commented on sapmon/payload/provider/sapnetweaver.py
> +    def _postProcessGetEnvironmentResults(self, sapResources: List[Dict]) -> List[Dict]:
yes, i have moved this logic out of _executeSoapApiForInstances and added logs for tracking latency in _actionGetSapHostAzRIdMapping

2021-10-05 07:51 UTC, amitsharma24 commented on sapmon/payload/provider/sapnetweaver.py
> +            postProcessResultsFunc = lambda results: self._postProcessGetEnvironmentResults(results)
done

2021-10-05 22:09 UTC, MikeFrei approved these changes

2021-10-06 05:05 UTC, merged