Sakattiy/aiops/aiops provider
hsridharan/AzureMonitorForSAPSolutions pull request #16
Opened 2021-09-07 08:51 UTC by saleelpk

The following classes are implemented to poll RH data.

1. Resource health helper class.
2. AIOps provider instance and check class
3. AIOps content json.

The data required for polling is obtained from the state file of individual providers.

2021-09-22 16:16 UTC, MikeFrei commented on sapmon/payload/aiops/aiopshelper.py
> +    tracer = None
just so you know, every variable that is initialized outside of the __init__ constructor in python is actually a static variable.  Only variables that are initialized in the constructor are member variables.

2021-09-22 16:17 UTC, MikeFrei commented on sapmon/payload/aiops/aiopshelper.py
> +    tracer = None
in other words, you do need to define any of these here if they are not static.  or if they *are* intended to be static, then you should not be using self.<variableName> in the constructor below.

2021-09-22 16:19 UTC, saleelpk commented on sapmon/payload/aiops/aiopshelper.py
> +    tracer = None
I intended to make them member variables. I think I might have done the same in other classes too. Will take care of all of them. Thanks for the insight!

2021-09-22 16:23 UTC, MikeFrei commented on sapmon/payload/aiops/aiopshelper.py
> +                "Could not fetch vm to computer names mapping. (%s)" % ex)
I am going to suggest you follow the more detailed exception stack logging pattern that Al enabled a while back, search for the string "exc_info" in the sapnetweaver.py file and you'll see what I mean.  Basically enables full stack trace for exceptions to get logged.

2021-09-22 16:25 UTC, saleelpk commented on sapmon/payload/aiops/aiopshelper.py
> +                "Could not fetch vm to computer names mapping. (%s)" % ex)
Will implement across all the files.

2021-09-22 16:25 UTC, MikeFrei commented on sapmon/payload/aiops/aiopshelper.py
> +            self.tracer.debug("List of computer names = %s" %
it is good that you are logging the list of compute names as debug.  I wonder if you're not missing the opportunity for more helpful info and error logging elsewhere in this function.  For example, if an exception is thrown, how do you know what VNet you were querying for?

2021-09-22 16:27 UTC, MikeFrei commented on sapmon/payload/aiops/aiopshelper.py
> +            self.tracer.info(
similar comment about logging usefulness.  You're not including anything in this info log that would be helpful for debugging, and the log itself only indicates that the query did not throw an exception.

How about logging the  # of results that were returned?  How about logging the # of computer Names that were included in the comma-delimited list?  Then at least you could have some indicator of whether you are getting the expected results back.

2021-09-22 16:29 UTC, saleelpk commented on sapmon/payload/aiops/aiopshelper.py
> +            self.tracer.debug("List of computer names = %s" %
Got it. I'll include more useful logs. I'll also log the ARG query before it is run.

2021-09-22 16:29 UTC, saleelpk commented on sapmon/payload/aiops/aiopshelper.py
> +            self.tracer.info(
Will take care of this.

2021-09-22 16:29 UTC, MikeFrei commented on sapmon/payload/aiops/aiopshelper.py
> +            self.tracer.debug("vNetId=%s" % vNetId)
make this log more useful and make it info and not debug.  At the minimum I would include the collectorVmId that was used in the query.

2021-09-22 16:58 UTC, MikeFrei requested changes
also, per our discussion, I think you will find it very helpful to have a common prefix in all of your log lines like "[AIOps]" so that when you query for these operational logs in production you will find it much easier to filter down to just relevant logs for your component area

2021-09-22 16:58 UTC, MikeFrei commented on sapmon/payload/aiops/aiopshelper.py
> +                errorMessage = 'Zero result was returned by ARG for the VM Id - %s.' % self.collectorVMId
if the VM *was* part of mor ethan one VNET, wouldn't it be helpful to log out the VNET Ids here?

2021-09-22 16:58 UTC, MikeFrei commented on sapmon/payload/aiops/azureresourcegraph.py
> +            if not self.__shouldRetry(argQueryResponse):
why is the __shouldRetry and __waitForQuotaReset logic interaction different for ARG vs. RH?

2021-09-22 16:58 UTC, MikeFrei commented on sapmon/payload/aiops/resourcehealth.py
> +                if self.__shouldRetry(e.response):
I *think* the way you implement this shouldRetry -> then waitForQuotaReset logic for RH is easier to read (to me) than the ARG one above

2021-09-23 20:44 UTC, saleelpk commented on sapmon/payload/aiops/aiopshelper.py
> +    tracer = None
Changed all the class variables to member variables.

2021-09-23 20:45 UTC, saleelpk commented on sapmon/payload/aiops/aiopshelper.py
> +            self.tracer.debug("List of computer names = %s" %
Added exc_info flag to all the error logging statements.

2021-09-23 20:45 UTC, saleelpk commented on sapmon/payload/aiops/aiopshelper.py
> +            self.tracer.info(
computerNames are now being logged at the entry point. Also the query is being logged now. Additionally the number of results returned is also logged.

2021-09-23 20:47 UTC, saleelpk commented on sapmon/payload/aiops/aiopshelper.py
> +            self.tracer.debug("vNetId=%s" % vNetId)
Detailed logs have been added with regards to vNetIds. The input vNetId is being logged. In case that was not provided, the collector VM vNet Id is being logged.

2021-09-23 20:47 UTC, saleelpk commented
> also, per our discussion, I think you will find it very helpful to have a common prefix in all of your log lines like "[AIOps]" so that when you query for these operational logs in production you will find it much easier to filter down to just relevant logs for your component area

Added appropriate log tags in each file.

2021-09-23 20:47 UTC, closed without merging

2021-09-23 20:49 UTC, saleelpk commented on sapmon/payload/aiops/aiopshelper.py
> +                errorMessage = 'Zero result was returned by ARG for the VM Id - %s.' % self.collectorVMId
This was a mistake from my part. I was supposed to remove the comment long ago. I discussed with Mani and he suggested that a VM cannot be a part of more than one VNet. I read up online and that seemed to be the case. I have edited the comment accordingly. 

Do let me know your thoughts on this one.

2021-09-23 20:49 UTC, saleelpk commented on sapmon/payload/aiops/azureresourcegraph.py
> +            if not self.__shouldRetry(argQueryResponse):
Made it same as RH.

2021-09-23 20:49 UTC, saleelpk commented on sapmon/payload/aiops/resourcehealth.py
> +                if self.__shouldRetry(e.response):
Made it same as RH

2021-09-24 16:14 UTC, saleelpk commented
Force pushed to maintain clean history.