PR to add non-HTTPS fallback for SAPNetWeaver collector provider as well as more granular latency logging
hsridharan/AzureMonitorForSAPSolutions pull request #2
Opened 2020-12-16 18:42 UTC by MikeFrei

PR against Harsha's subdomain feature branch to pull add a fallback to HTTP for SAPNetWeaver provider collector code if there is no valid HTTPS port configured for a given instance.  Also add some additional logging around remote dependency call latency so we can track how long these collector operations are taking.

2020-12-16 21:21 UTC, hsridharan commented on .gitignore
> +settings.json
I dont think we need to push .gitignore changes to the repo, It will be great if this can be removed?

2020-12-16 21:50 UTC, jasneetbhatti-msft requested changes

2020-12-16 21:50 UTC, jasneetbhatti-msft commented on sapmon/payload/provider/sapnetweaver.py
>      def validate(self) -> bool:
The `validate` method doesn't handle the http/https scenario. It should be able to fall back on the http protocol too.
I'm wondering if it is better to have the `getClient` method accept only the `hostname` and `instanceNr` and let it try out https first and return that client, else return the http client. We don't need the actions to decide what protocol to use; that feels like the responsibility of the client. We know the convention for constructing the port numbers from the `instanceNr` directly. Simplifies everything significantly.

2020-12-16 22:05 UTC, MikeFrei commented on sapmon/payload/provider/sapnetweaver.py
>              self.tracer.info("[%s] establishing connection to url: %s" % (self.fullName, url))
good catch, thanks will remove

2020-12-16 22:07 UTC, MikeFrei commented on sapmon/payload/provider/sapnetweaver.py
>      def validate(self) -> bool:
agree that would simply a lot.  Let me take another look here as I think I am not that comfortable yet with the different contexts the client is instantiated and what port data was available at that time.

2020-12-16 23:00 UTC, MikeFrei commented on sapmon/payload/helper/timeutils.py
> +#!/usr/bin/env python3
same one that is present from multiple other files in the helper folder, i just copied from there.

2020-12-16 23:01 UTC, MikeFrei commented on sapmon/payload/helper/timeutils.py
> +        return int((endTime - startTime) * 1000)
i can do this, although we have several other files that don't have this

2020-12-18 17:36 UTC, MikeFrei commented on .gitignore
> +settings.json
hey Harsha, I don't think this hurts anything and in fact it prevents me (or any other VS Code user) from having to make the same throwaway local changes over and over

2020-12-18 17:36 UTC, MikeFrei commented on sapmon/payload/helper/timeutils.py
> +        return int((endTime - startTime) * 1000)
this was done in latest iteration

2020-12-18 17:42 UTC, MikeFrei commented on sapmon/payload/provider/sapnetweaver.py
>      def validate(self) -> bool:
Per our discussion I think there is probably a larger refactoring to be done here that would separate responsibilities for discovering which instances to monitor and performing the actual check to fetch metrics for those instances.  Right now there is an implicit ordering that has to be performed with the instance check running first, and this is less than ideal.  But for now this latest iteration refactoring creates two different methods for creating a client:  

1. one method allows creation of a client by a specific hostname and instance # (or will use the default hostname/instanceNr properties the provider was initialized with), and attempt to connect on derived HTTPS port first before falling back to derived HTTP port
2. another method that allows creation of a client when caller already has host config for that hostname and knows which port/protocol to use.

2020-12-18 17:56 UTC, MikeFrei commented on sapmon/payload/provider/sapnetweaver.py
> +            hosts = [(hostConfig['hostname'],
@hsridharan  I have now changed this structure to return hostname, instance#, httpProtocol, httpPort.  I have removed subdomain since it seemed like it was more of an immutable property of the provider instance and hence we did not need to pass it around like it was a variable that could be different per instance.  In every place where it was referenced we were always assigning it from the self.providerInstance.sapSubdomain properties.  Let me know if I got this wrong.

2020-12-18 17:57 UTC, MikeFrei commented on sapmon/payload/provider/sapnetweaver.py
> +    def getFullyQualifiedDomainName(self, hostname: str) -> str:
@hsridharan I removed the subdomain param here since it seemed like we were really just using the member variable in all cases.

2020-12-18 19:29 UTC, jasneetbhatti-msft approved these changes

2020-12-18 21:53 UTC, hsridharan approved these changes

2020-12-18 21:53 UTC, merged