RFC changes
hsridharan/AzureMonitorForSAPSolutions pull request #9
Opened 2021-05-12 23:33 UTC by kavitha2270

RFC calls to SAP Application server changes-

- Earlier the calls were made through ABAP feature to Application server.
- A load balancer called "MESSAGE SERVER" is added for connection from a RFC request to individual Application Servers.
- A parameter "sapLogonGroup" is added so that the application type is recognized by the load balancer to connect to that particular application server. 
- original getConnection() method is renamed to _getApplicationServerConnection() to fetch the ABAP instance.
- loadbalancer instance is now fetched from _getMessageServerConnection() method

2021-05-13 15:09 UTC, MikeFrei commented on sapmon/payload/netweaver/rfcclient.py
> +        self.msserv = "36%s" % self.sapSysNr
hmm I am sorry this did not occur to me earlier but I think we may need to ensure that this instance number is padded with leading zeroes so that it is always exactly two digits long.  So if instanceNr is "1", then the msserv value here would be "3601"

2021-05-13 15:26 UTC, MikeFrei commented on sapmon/payload/netweaver/rfcclient.py
> +                                    Group = self.sapLogonGroup,
hmmm we should confirm that this is capitalized, since none of the other parameters are capitalized

2021-05-13 15:43 UTC, MikeFrei requested changes
for most part everything looks good!  Just a few small comments

2021-05-13 15:43 UTC, MikeFrei commented on sapmon/payload/netweaver/rfcclient.py
> +                                     mshost = self.fqdn,
let's fix indentation here to align with other parameters

2021-05-13 15:48 UTC, bluereign commented on sapmon/payload/netweaver/rfcclient.py
> +        except CommunicationError as e:
Why catch these exception specifically if all we're doing is raising them?  The one generic exception catch should be all we need.

2021-05-13 15:48 UTC, bluereign commented on sapmon/payload/netweaver/rfcclient.py
> +            connection = Connection(#ashost=self.fqdn,
Can we remove this commented out line?

2021-05-13 16:08 UTC, MikeFrei commented on sapmon/payload/netweaver/rfcclient.py
> +            connection = Connection(#ashost=self.fqdn,
maybe we can remove the commented out line from the function parameters but instead move it up to the comment two lines above about the direct application server logon parameters.  The problem is that the NW RFC package documentation is sparse and so I'd like to keep some documentation in the code about how to get this connection working in alternative modes, since it was a struggle to get this stuff working in the first place.

2021-05-13 16:18 UTC, kavitha2270 commented on sapmon/payload/netweaver/rfcclient.py
> +        self.msserv = "36%s" % self.sapSysNr
@MikeFrei, do mean by if sapSysNr is "1"?

2021-05-13 16:18 UTC, kavitha2270 commented on sapmon/payload/netweaver/rfcclient.py
> +                                    Group = self.sapLogonGroup,
I have tested this, will run one more round of testing.

2021-05-13 19:06 UTC, hsridharan commented on sapmon/payload/netweaver/rfcclient.py
> +                                     mshost = self.fqdn,
fix spacing  before and after = for sysnr

2021-05-13 19:06 UTC, hsridharan commented on sapmon/payload/netweaver/rfcclient.py
> +        self.msserv = "36%s" % self.sapSysNr
Are we doing string transformation here for self.sapSysNr. E.g: if in config has a value of 1 we zfill it as 01. I know we have that logic in sapnetweaver.py. Do we need it here as well?

2021-05-13 20:06 UTC, MikeFrei commented on sapmon/payload/netweaver/rfcclient.py
> +                                    client=self.sapClient,
actaully, python convention is specifically to NOT have spaces for named function parameters like this. I read this on several different python coding style guidelines

2021-05-13 20:08 UTC, hsridharan commented on sapmon/payload/netweaver/rfcclient.py
> +                                    client=self.sapClient,
@MikeFrei - Good to know that, So we should make it uniform - remove the spaces in all the lines.

2021-05-13 20:10 UTC, MikeFrei commented on sapmon/payload/netweaver/rfcclient.py
> +                                    client=self.sapClient,
only when passing named function parameters like this.  In other places (like a normal line of code within a function where you set x = y  the style guidelines advise having spaces.  Frankly I don't find it very consistent but this seems to be the convention

2021-05-13 20:11 UTC, MikeFrei commented on sapmon/payload/provider/sapnetweaver.py
>          # RFC connections against direct application server instances can only be made to 'ABAP' instances
ah, sorry let's fix the 'ABAP' comment here on line 278

2021-05-13 20:13 UTC, kavitha2270 commented on sapmon/payload/netweaver/rfcclient.py
> +                                    client=self.sapClient,
ok, I will remove spaces.

2021-05-13 20:14 UTC, MikeFrei commented on sapmon/payload/provider/sapnetweaver.py
> +        return dispatcherInstances[0]
oh good catch Harsha.  Yes kavitha, you want the same check here we were doing before:

if (len(dispatcherInstances) == 0):
       raise Exception("No MESSAGESERVER instance found for %s" % self.sapSid)

2021-05-13 20:15 UTC, MikeFrei commented on sapmon/payload/provider/sapnetweaver.py
> +        return dispatcherInstances[0]
although in fairness this should never happen because according to Ram MESSAGESERVER is always required for any SAP system

2021-05-13 20:18 UTC, kavitha2270 commented on sapmon/payload/provider/sapnetweaver.py
> +        return dispatcherInstances[0]
yeah ok, I went with the assumption that load balancer will be available always.

2021-05-13 20:57 UTC, MikeFrei commented on sapmon/payload/netweaver/rfcclient.py
> +        self.msserv = "36%s" % self.sapSysNr
we are not doing any string tranformation inside rfcclient.  I do not know if we are transforming the value before we pass it into the metric client factory.  I know it is being passed as a string.

2021-05-14 19:37 UTC, MikeFrei approved these changes
everything looks good to me Kavitha, thank you for making the changes!

2021-05-14 20:28 UTC, hsridharan commented on sapmon/payload/netweaver/rfcclient.py
> +
looks like there is an empty space here. Can u please remove it?

2021-05-18 17:55 UTC, merged